### ISSUE TITLE
Missing gem colorize?

### ISSUE THREAD

**Issue by kevintelford** [wagn/wagn#788]
I ran the following using wagn 1.20.2 (Ruby 2.3.2)
```
wagn new mysite -d postgresql
cd mysite
wagn seed
```
Which resulted in
```
rake aborted!
LoadError: cannot load such file -- colorize
```
After adding `gem 'colorize'` to the Gemfile and rerunning `bundle install` the `wagn seed` command now works.

**Comment by xithan** [comment]
fixed in 1.20.3
