### ISSUE TITLE
Is wagn project alive?

### ISSUE THREAD

**Issue by tukanos** [wagn/wagn#814]
Hello Ethan,
Is wagn alive?  The commits suggest that yes.  All the information seems to be really old and the wagn.org is not updated anymore.  All there seems to be some connection to [wikirate](http://wikirate.org/).

Regards,

Patrik

**Comment by ethn** [comment]
Very much so, but it's being renamed from "Wagn" to "Decko" (see https://github.com/decko-commons/decko).  We've been waiting until the master branch over there stabilizes a bit to link prominently from this repo to that one.  It's very close, and things are moving rapidly. We just put out a 3.1 gem on ruby gems last night.

WikiRate.org is running on wagn/decko and has been driving its development in recent years, so a lot of the issue tracking moved off into their team tools, but we're going to be doing a major overhaul of wagn.org as decko.org in 2018.

**Comment by tukanos** [comment]
Great news!  Thank you for the heads-up.
